---
version: "3"
services:
  # run single validator kava node to provide a local kava network for development and testing of the blockscout service end to end
  kava:
    image: kava/kava:latest
    entrypoint: /docker/kava/kava-entrypoint.sh
    env_file: .env
    volumes:
      - ./kava:/docker/kava
    ports:
      - "${KAVA_HOST_COSMOS_RPC_PORT}:${KAVA_CONTAINER_COSMOS_RPC_PORT}"
      - "${KAVA_HOST_EVM_RPC_PORT}:${KAVA_CONTAINER_EVM_RPC_PORT}"
    # expose ports for other services to be able to connect to within
    # the default docker-compose network
    expose:
      - "${KAVA_CONTAINER_COSMOS_RPC_PORT}"
      - "${KAVA_CONTAINER_EVM_RPC_PORT}"
  postgres:
    env_file: .env
    build: "./db"
    volumes:
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
  blockscout:
    build: "./blockscout"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "${BLOCKSCOUT_HOST_PORT}:${BLOCKSCOUT_CONTAINER_PORT}"
