name: Continuous Integration (Default Checks)

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      # load/create a cache of docker images from previous job runs (if any)
      - name: cache docker images
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: build production docker image
        run: make build
      # Finally, "Post Run jpribyl action-docker-layer-caching@v0.1.1",
      # which is the process of saving the docker cache, will be executed.
